name: aquapact
description: 'AquaPact Flutter project.'
publish_to: 'none'

version: 0.1.4+14

environment:
  sdk: ^3.9.0
  flutter: 3.38.0

dependencies:
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^5.0.1
  get_it: ^9.0.5
  google_fonts: ^6.3.2
  home_widget: ^0.8.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.2
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  time_range_picker: ^2.3.1
  timezone: ^0.10.1
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  build_runner: ^2.10.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  objectbox_generator: ^5.0.2

flutter:
  assets:
    - assets/png/
    - assets/fonts/
  generate: true
  uses-material-design: true

objectbox:
  output_dir: vendor/objectbox
